# Generated by Django 3.2.3 on 2021-06-05 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_bookmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookModel',
            new_name='Book',
        ),
    ]
