# Generated by Django 3.2.3 on 2021-06-06 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_bookmodel_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='description',
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
    ]
