# Generated by Django 3.2.3 on 2021-06-06 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_book_geeks_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='geeks_field',
        ),
        migrations.AlterField(
            model_name='book',
            name='course',
            field=models.CharField(choices=[('null', 'Select Branch'), ('BCA', 'BCA'), ('BBA', 'BBA'), ('MCA', 'MCA'), ('ME', 'B.Tech. ME'), ('CSE', 'B.Tech. CSE'), ('EI', 'B.Tech. EI'), ('EC', 'B.Tech. EC'), ('IT', 'B.Tech. IT'), ('CE', 'B.Tech. CIVIL'), ('EE', 'B.Tech. ELECTRICAL ENGG')], default='null', max_length=255),
        ),
        migrations.AlterField(
            model_name='book',
            name='semester',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], default='1', max_length=5),
        ),
    ]
