# Generated by Django 3.2 on 2021-06-06 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='book',
            new_name='book_file',
        ),
    ]
