# Generated by Django 3.2 on 2021-06-06 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20210607_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book',
            field=models.ImageField(upload_to='books/'),
        ),
    ]
