# Generated by Django 3.2 on 2021-06-06 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20210607_0230'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='img',
            field=models.ImageField(default='test', upload_to='image'),
            preserve_default=False,
        ),
    ]
