# Generated by Django 3.2.3 on 2021-06-07 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_book_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='images')),
                ('pdf', models.FileField(upload_to='pdfs')),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
