# Generated by Django 3.2.3 on 2021-06-07 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_bookmodel_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmodel',
            name='image',
        ),
    ]
