# Generated by Django 3.2.3 on 2021-06-07 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_remove_bookmodel_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(choices=[('null', 'Select Branch'), ('BCA', 'BCA'), ('BBA', 'BBA'), ('MCA', 'MCA'), ('ME', 'B.Tech. ME'), ('CSE', 'B.Tech. CSE'), ('EI', 'B.Tech. EI'), ('EC', 'B.Tech. EC'), ('IT', 'B.Tech. IT'), ('CE', 'B.Tech. CIVIL'), ('EE', 'B.Tech. ELECTRICAL ENGG')], default='null', max_length=255)),
                ('semester', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], default='1', max_length=5)),
                ('pdf', models.FileField(upload_to='syllabus')),
            ],
        ),
    ]
