# Generated by Django 3.2.3 on 2021-06-18 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_previousyear'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='syllabus',
            name='semester',
        ),
    ]
