# Generated by Django 3.2 on 2021-06-26 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_remove_syllabus_semester'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestModel',
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='pdf',
            field=models.FileField(upload_to='static/media/pdfs'),
        ),
        migrations.AlterField(
            model_name='previousyear',
            name='pdf',
            field=models.FileField(upload_to='static/media/previousYear'),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='pdf',
            field=models.FileField(upload_to='static/media/syllabus'),
        ),
    ]
