# Generated by Django 3.2 on 2021-06-27 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20210627_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='pdf',
            field=models.FileField(upload_to='pdfs'),
        ),
        migrations.AlterField(
            model_name='previousyear',
            name='pdf',
            field=models.FileField(upload_to='previousYear'),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='pdf',
            field=models.FileField(upload_to='syllabus'),
        ),
    ]
